#!/bin/bash

VM_NAME=${1%.*}

vboxmanage natnetwork add --netname mynet --network "192.168.15.0/24" --enable --dhcp on
vboxmanage modifyvm $VM_NAME --firmware efi --memory 2048 --cpus 1 --vram 16 --clipboard bidirectional --draganddrop bidirectional
