#!/bin/bash

# if u use btrfs please disable copy-on-write for folder with virtual drives
# sudo chattr +C .

VM_NAME=${1%.*}
DRIVE_NAME=$1
ISO_PATH=$2

# cleanup
vboxmanage unregistervm $VM_NAME
rm -rf "$HOME/VirtualBox VMs/$VM_NAME"

# init
vboxmanage createvm --name $VM_NAME --register # --ostype=linux

# storage
vboxmanage storagectl $VM_NAME --name "SATA Controller" --add sata --portcount 1 --bootable on
vboxmanage storagectl $VM_NAME --name "IDE Controller" --add ide --controller PIIX4 --hostiocache on --portcount 2
if [ ! -f $DRIVE_NAME ]; then
  vbox-img createbase --filename $DRIVE_NAME --size 42949672960 --format VDI # 40GB
fi
vboxmanage storageattach $VM_NAME --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium $DRIVE_NAME

if [ -z $ISO_PATH ]; then
  vboxmanage storageattach $VM_NAME --storagectl "IDE Controller" --port 1 --device 1 --type dvddrive --medium none
else
  vboxmanage storageattach $VM_NAME --storagectl "IDE Controller" --port 1 --device 1 --type dvddrive --medium $ISO_PATH
fi

# network
vboxmanage natnetwork add --netname mynet --network "192.168.15.0/24" --enable --dhcp on

# add all the stuff
vboxmanage modifyvm $VM_NAME --firmware efi --memory 2048 --cpus 2 --vram 16 --nic1 nat --nic2 natnetwork --nat-network2 mynet
